// Generated by jimuctl studio export. DO NOT EDIT.
export const STUDIO_CONTRACT_VERSION = "1.0.0" as const;

export interface StudioRequestMap {
  "studio.audit.list": { "cursor"?: string; "limit"?: number; "search"?: string };
  "studio.contract.get": undefined;
  "studio.identity.roles.assign": { "expected_version": number; "idempotency_key": string };
  "studio.identity.roles.create": { "display_name": string; "idempotency_key": string; "key": string };
  "studio.identity.roles.list": { "cursor"?: string; "limit"?: number; "search"?: string };
  "studio.identity.roles.revoke": { "expected_version": number; "idempotency_key": string };
  "studio.identity.roles.update": { "display_name": string; "expected_version": number; "idempotency_key": string };
  "studio.identity.users.create": { "display_name": string; "email": string; "id": string; "idempotency_key": string };
  "studio.identity.users.list": { "cursor"?: string; "limit"?: number; "search"?: string };
  "studio.identity.users.status": { "confirmation": "DISABLE_USER"; "expected_version": number; "idempotency_key": string; "status": "active" | "disabled" };
  "studio.metadata.apply": { "confirmation": "APPLY_MIGRATION"; "entities": Array<{ "code": string; "fields": Array<{ "code": string; "data_type": string; "read_only"?: boolean; "required"?: boolean }>; "kind"?: string; "name": string; "version": number }>; "idempotency_key": string };
  "studio.metadata.entities.list": { "cursor"?: string; "limit"?: number; "search"?: string };
  "studio.metadata.entities.put": { "entity": { "code": string; "fields": Array<{ "code": string; "data_type": string; "read_only"?: boolean; "required"?: boolean }>; "kind"?: string; "name": string; "version": number }; "expected_version": number; "idempotency_key": string };
  "studio.metadata.plan": { "entities": Array<{ "code": string; "fields": Array<{ "code": string; "data_type": string; "read_only"?: boolean; "required"?: boolean }>; "kind"?: string; "name": string; "version": number }>; "idempotency_key": string };
  "studio.quota.discrepancies.list": { "cursor"?: string; "limit"?: number; "search"?: string };
  "studio.quota.plans.list": { "cursor"?: string; "limit"?: number; "search"?: string };
  "studio.quota.plans.publish": { "confirmation": "PUBLISH_QUOTA_PLAN"; "expected_version": number; "idempotency_key": string; "plan": { "code": string; "effective_at": string; "limits": { [key: string]: unknown }; "version": number; "window_seconds": number } };
  "studio.quota.usage.list": { "cursor"?: string; "limit"?: number; "search"?: string };
  "studio.workflow.runs.cancel": { "confirmation": "CANCEL_RUN"; "expected_version": number; "idempotency_key": string };
  "studio.workflow.runs.list": { "cursor"?: string; "limit"?: number; "search"?: string };
  "studio.workflow.tasks.retry": { "confirmation": "RETRY_TASK"; "expected_version": number; "idempotency_key": string };
}

export interface StudioResponseMap {
  "studio.audit.list": { "items": Array<{ "action": string; "actor_user_id": string; "details": { [key: string]: unknown }; "id": string; "occurred_at": string; "redacted_paths": Array<string>; "target_id": string; "target_type": string }>; "next_cursor"?: string };
  "studio.contract.get": { [key: string]: unknown };
  "studio.identity.roles.assign": { "display_name": string; "email"?: string; "id": string; "roles": Array<string>; "status": "active" | "disabled"; "version": number };
  "studio.identity.roles.create": { "display_name": string; "key": string; "system": boolean; "version": number };
  "studio.identity.roles.list": { "items": Array<{ "display_name": string; "key": string; "system": boolean; "version": number }>; "next_cursor"?: string };
  "studio.identity.roles.revoke": { "display_name": string; "email"?: string; "id": string; "roles": Array<string>; "status": "active" | "disabled"; "version": number };
  "studio.identity.roles.update": { "display_name": string; "key": string; "system": boolean; "version": number };
  "studio.identity.users.create": { "display_name": string; "email"?: string; "id": string; "roles": Array<string>; "status": "active" | "disabled"; "version": number };
  "studio.identity.users.list": { "items": Array<{ "display_name": string; "email"?: string; "id": string; "roles": Array<string>; "status": "active" | "disabled"; "version": number }>; "next_cursor"?: string };
  "studio.identity.users.status": { "display_name": string; "email"?: string; "id": string; "roles": Array<string>; "status": "active" | "disabled"; "version": number };
  "studio.metadata.apply": Array<{ "entity_code": string; "plan_code": string; "requires_confirmation": boolean; "risk": string; "summary": string }>;
  "studio.metadata.entities.list": { "items": Array<{ "code": string; "fields": Array<{ "code": string; "data_type": string; "read_only"?: boolean; "required"?: boolean }>; "kind"?: string; "name": string; "version": number }>; "next_cursor"?: string };
  "studio.metadata.entities.put": { "code": string; "fields": Array<{ "code": string; "data_type": string; "read_only"?: boolean; "required"?: boolean }>; "kind"?: string; "name": string; "version": number };
  "studio.metadata.plan": Array<{ "entity_code": string; "plan_code": string; "requires_confirmation": boolean; "risk": string; "summary": string }>;
  "studio.quota.discrepancies.list": { "items": Array<{ "enforcement_total": number; "from": string; "id": string; "ledger_total": number; "plan_code": string; "plan_version": number; "route": string; "unit": string; "until": string }>; "next_cursor"?: string };
  "studio.quota.plans.list": { "items": Array<{ "code": string; "effective_at": string; "limits": { [key: string]: unknown }; "version": number; "window_seconds": number }>; "next_cursor"?: string };
  "studio.quota.plans.publish": { "code": string; "effective_at": string; "limits": { [key: string]: unknown }; "version": number; "window_seconds": number };
  "studio.quota.usage.list": { "items": Array<{ "occurred_at": string; "plan_code": string; "plan_version": number; "quantity": number; "route": string; "unit": string }>; "next_cursor"?: string };
  "studio.workflow.runs.cancel": { "id": string; "state": string; "updated_at": string; "version": number; "workflow": string };
  "studio.workflow.runs.list": { "items": Array<{ "id": string; "state": string; "updated_at": string; "version": number; "workflow": string }>; "next_cursor"?: string };
  "studio.workflow.tasks.retry": { "id": string; "state": string; "updated_at": string; "version": number; "workflow": string };
}

const operations = {
  "studio.audit.list": {
    "method": "GET",
    "path": "/studio/v1/audit"
  },
  "studio.contract.get": {
    "method": "GET",
    "path": "/studio/v1/openapi.json"
  },
  "studio.identity.roles.assign": {
    "method": "PUT",
    "path": "/studio/v1/identity/users/{id}/roles/{role}"
  },
  "studio.identity.roles.create": {
    "method": "POST",
    "path": "/studio/v1/identity/roles"
  },
  "studio.identity.roles.list": {
    "method": "GET",
    "path": "/studio/v1/identity/roles"
  },
  "studio.identity.roles.revoke": {
    "method": "DELETE",
    "path": "/studio/v1/identity/users/{id}/roles/{role}"
  },
  "studio.identity.roles.update": {
    "method": "PATCH",
    "path": "/studio/v1/identity/roles/{key}"
  },
  "studio.identity.users.create": {
    "method": "POST",
    "path": "/studio/v1/identity/users"
  },
  "studio.identity.users.list": {
    "method": "GET",
    "path": "/studio/v1/identity/users"
  },
  "studio.identity.users.status": {
    "method": "PATCH",
    "path": "/studio/v1/identity/users/{id}/status"
  },
  "studio.metadata.apply": {
    "method": "POST",
    "path": "/studio/v1/metadata/apply"
  },
  "studio.metadata.entities.list": {
    "method": "GET",
    "path": "/studio/v1/metadata/entities"
  },
  "studio.metadata.entities.put": {
    "method": "PUT",
    "path": "/studio/v1/metadata/entities/{code}"
  },
  "studio.metadata.plan": {
    "method": "POST",
    "path": "/studio/v1/metadata/plan"
  },
  "studio.quota.discrepancies.list": {
    "method": "GET",
    "path": "/studio/v1/quota/discrepancies"
  },
  "studio.quota.plans.list": {
    "method": "GET",
    "path": "/studio/v1/quota/plans"
  },
  "studio.quota.plans.publish": {
    "method": "POST",
    "path": "/studio/v1/quota/plans"
  },
  "studio.quota.usage.list": {
    "method": "GET",
    "path": "/studio/v1/quota/usage"
  },
  "studio.workflow.runs.cancel": {
    "method": "POST",
    "path": "/studio/v1/workflows/runs/{id}/cancel"
  },
  "studio.workflow.runs.list": {
    "method": "GET",
    "path": "/studio/v1/workflows/runs"
  },
  "studio.workflow.tasks.retry": {
    "method": "POST",
    "path": "/studio/v1/workflows/tasks/{id}/retry"
  }
} as const;

export class StudioClient {
  constructor(private readonly baseURL: string, private readonly token: string) {
	const parsedBaseURL = new URL(baseURL);
	if (!/^https?:$/.test(parsedBaseURL.protocol) || parsedBaseURL.username || parsedBaseURL.password) throw new Error("Studio base URL must be an HTTP(S) origin without credentials");
	if (!token || token.length > 16384 || !/^[A-Za-z0-9._~+\/-]+=*$/.test(token)) throw new Error("A safe opaque bearer token is required");
    if (!baseURL || !token || token.length > 16384 || /[\r\n]/.test(token)) throw new Error("Studio base URL and safe opaque bearer token are required");
  }

  withToken(token: string): StudioClient { return new StudioClient(this.baseURL, token); }

  async request<K extends keyof StudioRequestMap>(operation: K, pathParameters: Record<string, string>, input: StudioRequestMap[K]): Promise<StudioResponseMap[K]> {
    const spec = operations[operation];
    let path = spec.path as string;
    for (const [name, value] of Object.entries(pathParameters)) path = path.replace(`{${name}}`, encodeURIComponent(value));
    if (path.includes("{")) throw new Error("Missing Studio path parameter");
	const url = new URL(path, this.baseURL);
	if (spec.method === "GET" && input && typeof input === "object") {
	  for (const [name, value] of Object.entries(input)) if (value !== undefined) url.searchParams.set(name, String(value));
	}
    const response = await fetch(url, {
      method: spec.method,
      headers: { "Authorization": `Bearer ${this.token}`, "Accept": "application/json", ...(spec.method === "GET" ? {} : { "Content-Type": "application/json" }) },
      body: spec.method === "GET" ? undefined : JSON.stringify(input),
    });
    if (!response.ok) throw new StudioAPIError(response.status, await response.text());
    if (response.status === 204) return undefined as unknown as StudioResponseMap[K];
    return await response.json() as StudioResponseMap[K];
  }
}

export class StudioAPIError extends Error {
  constructor(public readonly status: number, public readonly responseBody: string) { super(`Studio API ${status}`); }
}
